# Generated by Django 5.0.7 on 2024-08-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0003_jsondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondocument',
            name='original_filename',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
