# Generated by Django 5.0.7 on 2024-08-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0004_jsondocument_original_filename'),
    ]

    operations = [
    ]
