# Generated by Django 5.0.7 on 2024-08-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_extractor', '0006_auto_20240801_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='jsondocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jsons/'),
        ),
    ]
